/**
 * build:site — generates site/docs.html from lib/web/README.md
 *
 * Zero-dependency markdown renderer tailored to the README of @li3/web.
 * Run from the repository root: `pnpm build:site`
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const readmePath = resolve(here, '../lib/web/README.md');
const outPath = resolve(here, 'docs.html');

const markdown = readFileSync(readmePath, 'utf8');

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/<[^>]*>/g, '')
    .replace(/[`*'"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function inline(text: string): string {
  let out = escapeHtml(text);
  const code: string[] = [];
  out = out.replace(/`([^`]+)`/g, (_m, c) => {
    code.push(c);
    return '\u0001' + (code.length - 1) + '\u0002';
  });
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_m, label, href) => {
    const target = href.startsWith('http') ? ' target="_blank" rel="noopener noreferrer"' : '';
    return `<a href="${href}"${target}>${label}</a>`;
  });
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/\u0001(\d+)\u0002/g, (_m, i) => `<code>${code[Number(i)]}</code>`);
  return out;
}

function renderTable(rows: string[][]): string {
  const [head, , ...body] = rows;
  const th = head.map((c) => `<th>${inline(c)}</th>`).join('');
  const trs = body.map((r) => '<tr>' + r.map((c) => `<td>${inline(c)}</td>`).join('') + '</tr>').join('\n');
  return `<table>\n<thead><tr>${th}</tr></thead>\n<tbody>\n${trs}\n</tbody>\n</table>`;
}

function renderMarkdown(md: string): string {
  const lines = md.split('\n');
  const html: string[] = [];
  let para: string[] = [];
  let list: string[] | null = null;
  let table: string[][] | null = null;

  const flushPara = () => {
    if (para.length) {
      html.push('<p>' + para.map(inline).join('<br />\n') + '</p>');
      para = [];
    }
  };
  const flushList = () => {
    if (list) {
      html.push('<ul>\n' + list.map((item) => '<li>' + inline(item) + '</li>').join('\n') + '\n</ul>');
      list = null;
    }
  };
  const flushTable = () => {
    if (table) {
      html.push(renderTable(table));
      table = null;
    }
  };
  const flushAll = () => {
    flushPara();
    flushList();
    flushTable();
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.startsWith('```')) {
      flushAll();
      const lang = line.slice(3).trim();
      const buf: string[] = [];
      while (++i < lines.length && !lines[i].startsWith('```')) buf.push(lines[i]);
      html.push(`<pre><code class="language-${lang || 'text'}">${escapeHtml(buf.join('\n'))}</code></pre>`);
      continue;
    }

    if (/^\s*---+\s*$/.test(line)) {
      flushAll();
      html.push('<hr />');
      continue;
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(line);
    if (heading) {
      flushAll();
      const level = heading[1].length;
      const text = heading[2].trim();
      const id = slugify(text);
      html.push(`<h${level} id="${id}"><a href="#${id}" class="anchor">${inline(text)}</a></h${level}>`);
      continue;
    }

    if (/^\s*\|.*\|\s*$/.test(line)) {
      flushPara();
      flushList();
      const cells = line.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
      if (/^:?-{2,}:?$/.test(cells[0] || '') && table === null) continue; // stray separator
      (table ||= []).push(cells);
      continue;
    }
    flushTable();

    const listItem = /^\s*[-*]\s+(.*)$/.exec(line);
    if (listItem) {
      flushPara();
      (list ||= []).push(listItem[1].trim());
      continue;
    }
    flushList();

    if (!line.trim()) {
      flushPara();
      continue;
    }

    para.push(line.trim());
  }

  flushAll();
  return html.join('\n');
}

const body = renderMarkdown(markdown);

const page = `<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Lithium Docs - @li3/web</title>
  <meta name="description" content="Complete documentation for @li3/web: template syntax, components, reactivity, props, events and extensions." />
  <!-- Generated by \`pnpm build:site\` from lib/web/README.md. Do not edit by hand. -->
</head>

<body class="font-sans text-gray-900 antialiased bg-white">
  <nav class="flex justify-between items-center px-8 py-4 bg-white border-b border-gray-100 sticky top-0 z-10">
    <a href="/" class="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">Li³</a>
    <div class="hidden md:flex gap-8">
      <a href="/" class="text-gray-600 hover:text-lithium transition-colors font-medium">Home</a>
      <a href="https://github.com/apphorde/lithium" target="_blank" rel="noopener noreferrer"
        class="text-gray-600 hover:text-lithium transition-colors font-medium">GitHub</a>
    </div>
  </nav>

  <main class="docs max-w-4xl mx-auto px-8 py-16">
    ${body}
  </main>

  <footer class="bg-gray-900 text-gray-400 py-12 px-8">
    <div class="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
      <div>
        <h3 class="text-white font-bold text-xl mb-2">Lithium</h3>
        <p>Pure Web APIs, Beautifully Extended</p>
      </div>
      <div class="flex gap-8 text-sm">
        <a href="https://github.com/apphorde/lithium" target="_blank" rel="noopener noreferrer"
          class="hover:text-white transition-colors">GitHub</a>
        <a href="/" class="hover:text-white transition-colors">Home</a>
      </div>
      <p class="text-sm">Released under the MIT License</p>
    </div>
  </footer>

  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          backgroundImage: {
            'gradient-primary': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            'gradient-accent': 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
          },
          colors: {
            lithium: '#667eea',
            'lithium-dark': '#764ba2',
          },
        },
      },
    };
  </script>
  <style>
    .docs h1 { font-size: 2.5rem; font-weight: 700; margin: 0 0 1.5rem; line-height: 1.2; }
    .docs h2 { font-size: 1.9rem; font-weight: 700; margin: 3rem 0 1rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; line-height: 1.25; }
    .docs h3 { font-size: 1.35rem; font-weight: 700; margin: 2rem 0 0.75rem; line-height: 1.3; }
    .docs h4 { font-size: 1.1rem; font-weight: 700; margin: 1.5rem 0 0.5rem; }
    .docs .anchor { color: inherit; text-decoration: none; }
    .docs .anchor:hover { color: #667eea; }
    .docs p { margin: 0.75rem 0; line-height: 1.7; color: #374151; }
    .docs ul { margin: 0.75rem 0 0.75rem 1.5rem; list-style: disc; color: #374151; }
    .docs li { margin: 0.35rem 0; line-height: 1.6; }
    .docs li ul { margin-top: 0.25rem; }
    .docs a { color: #667eea; text-decoration: underline; }
    .docs hr { margin: 2.5rem 0; border: none; border-top: 1px solid #e5e7eb; }
    .docs code { background: #f3f4f6; color: #764ba2; border-radius: 0.3rem; padding: 0.1rem 0.35rem; font-size: 0.875em; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
    .docs pre { background: #111827; color: #d1fae5; border-radius: 0.75rem; padding: 1.25rem; overflow-x: auto; margin: 1rem 0; font-size: 0.85rem; line-height: 1.6; }
    .docs pre code { background: transparent; color: inherit; padding: 0; font-size: inherit; }
    .docs table { width: 100%; border-collapse: collapse; margin: 1.25rem 0; font-size: 0.9rem; display: block; overflow-x: auto; }
    .docs thead, .docs tbody { display: table; width: 100%; }
    .docs th { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid #d1d5db; font-weight: 700; white-space: nowrap; }
    .docs td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
  </style>
</body>

</html>
`;

writeFileSync(outPath, page);
console.log(`docs.html generated (${page.length} bytes) from ${readmePath}`);
