name: Publish to CDN
on:
  push:
    branches:
      - main
    paths:
      - '*.json'
      - '*.yaml'
      - '*.js'
      - '*.ts'
      - 'lib/**'
      - '.github/**'

jobs:
  publish-apphorde:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build packages
        run: |
          set -e
          which pnpm && echo 'pnpm OK' || npm i -g pnpm
          pnpm i
          pnpm nx run-many -t build,tsc,test

      - name: Publish to AppHorde Registry
        env:
          CDN_API_URL: ${{ secrets.CDN_API_URL }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
        run: |
          for pkg in $(ls -1 lib); do
            echo -n $pkg...
            curl -sS --fail -H "Authorization: ${{ env.CDN_API_KEY }}" -X POST ${{ env.CDN_API_URL }}/library/@li3/$pkg@0.0.0 --data-binary @lib/$pkg/index.js
          done
