name: Publish to NPM
on:
  push:
    branches:
      - main
    paths:
      - "*.json"
      - "*.yaml"
      - "*.js"
      - "*.ts"
      - "lib/**"
      - ".github/**"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build packages and publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -e
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          echo "//registry.npmjs.org/:always-auth=true" >> .npmrc
          which pnpm && echo 'pnpm OK' || npm i -g pnpm
          pnpm i && pnpx nx run-many -t publish
