name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - html-parser
          - web
          - reactive
          - sfc

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - run: cd ${{ matrix.package }}

      - name: Bundle
        run: npx rollup -c rollup.config.mjs

      - name: Publish to AppHorde Registry
        run: >
          curl -sS --fail -H "Authorization: ${{ env.CDN_API_KEY }}" -X POST ${{ env.CDN_API_URL }}/library/@lithium/${{ matrix.package }}@latest --data-binary @index.js
        env:
          CDN_API_URL: ${{ secrets.CDN_API_URL }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
