name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build packages
        run: |
          npm ci && npx nx run-many -t build

      - name: Publish to AppHorde Registry
        working-directory: lib/${{ matrix.package }}
        env:
          CDN_API_URL: ${{ secrets.CDN_API_URL }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
        run: |
          for package in (html-parser web reactive sfc cli); do
            curl -sS --fail -H "Authorization: ${{ env.CDN_API_KEY }}" -X POST ${{ env.CDN_API_URL }}/library/@lithium/${{ $package }}@latest --data-binary @lib/$package/index.js
          done
