name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build packages
        run: |
          set -e
          which pnpm && echo 'pnpm OK' || npm i -g pnpm
          pnpm i && pnpx nx run-many -t build,test

      - name: Publish to AppHorde Registry
        env:
          CDN_API_URL: ${{ secrets.CDN_API_URL }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
        run: |
          for pkg in cli html-parser reactive scope sfc store web; do
            echo -n $pkg...
            curl -sS --fail -H "Authorization: ${{ env.CDN_API_KEY }}" -X POST ${{ env.CDN_API_URL }}/library/@lithium/$pkg@0.0.0 --data-binary @lib/$pkg/dist/index.js
          done
