name: Publish website

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish site
        env:
          DEPLOY_API_URL: ${{ secrets.DEPLOY_API_URL }}
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        run: |
          tar -cz -f - -C site --exclude .git/ --exclude node_modules/ . | curl -sS -H "Authorization: $DEPLOY_API_KEY" $DEPLOY_API_URL --data-binary @-
