name: Publish website
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "site/**"
      - "docs/**"
      - "lib/**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    permissions:
      contents: read
      packages: write
    with:
      baseImage: cloud-cli/node:latest
      withSha: false
      withTag: true
      type: static
      path: "site"
      buildCommand: cd .. && npm i -g pnpm && pnpm i && npx nx run-many -t build && npm run docs
